version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: UTC
    labels:
      - "dependabot"
      - "composer"
    open-pull-requests-limit: 10
