name: Combine Dependabot PRs

on:
  schedule:
    - cron: '0 7 * * *' # Daily at 07:00
  workflow_dispatch: # allows you to manually trigger the workflow

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  combine-prs:
    runs-on: ubuntu-latest

    steps:
      - name: combine-prs
        id: combine-prs
        uses: github/combine-prs@v5.0.0
        with:
          pr_title: 'Combined Dependabot PRs'
